name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        endpoint: http://www.baidu.com
        git-secret: ${{secrets.git_secrets}}
      env:
        env-endpoint: this is env-endpoint
        env-git-secret: ${{secrets.git_secrets}}

    - name: Build
      run: |
        npm install

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: build
        github_token: ${{ secrets.GITHUB_TOKEN }}
